// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fk-atlas.proto

package fk_atlas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SensorType int32

const (
	SensorType_SENSOR_NONE SensorType = 0
	SensorType_SENSOR_PH   SensorType = 1
	SensorType_SENSOR_TEMP SensorType = 2
	SensorType_SENSOR_ORP  SensorType = 3
	SensorType_SENSOR_DO   SensorType = 4
	SensorType_SENSOR_EC   SensorType = 5
)

var SensorType_name = map[int32]string{
	0: "SENSOR_NONE",
	1: "SENSOR_PH",
	2: "SENSOR_TEMP",
	3: "SENSOR_ORP",
	4: "SENSOR_DO",
	5: "SENSOR_EC",
}

var SensorType_value = map[string]int32{
	"SENSOR_NONE": 0,
	"SENSOR_PH":   1,
	"SENSOR_TEMP": 2,
	"SENSOR_ORP":  3,
	"SENSOR_DO":   4,
	"SENSOR_EC":   5,
}

func (x SensorType) String() string {
	return proto.EnumName(SensorType_name, int32(x))
}

func (SensorType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_822d05f6175684bb, []int{0}
}

type QueryType int32

const (
	QueryType_QUERY_NONE QueryType = 0
)

var QueryType_name = map[int32]string{
	0: "QUERY_NONE",
}

var QueryType_value = map[string]int32{
	"QUERY_NONE": 0,
}

func (x QueryType) String() string {
	return proto.EnumName(QueryType_name, int32(x))
}

func (QueryType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_822d05f6175684bb, []int{1}
}

type CalibrationOperation int32

const (
	CalibrationOperation_CALIBRATION_NONE   CalibrationOperation = 0
	CalibrationOperation_CALIBRATION_STATUS CalibrationOperation = 1
	CalibrationOperation_CALIBRATION_CLEAR  CalibrationOperation = 2
	CalibrationOperation_CALIBRATION_SET    CalibrationOperation = 3
)

var CalibrationOperation_name = map[int32]string{
	0: "CALIBRATION_NONE",
	1: "CALIBRATION_STATUS",
	2: "CALIBRATION_CLEAR",
	3: "CALIBRATION_SET",
}

var CalibrationOperation_value = map[string]int32{
	"CALIBRATION_NONE":   0,
	"CALIBRATION_STATUS": 1,
	"CALIBRATION_CLEAR":  2,
	"CALIBRATION_SET":    3,
}

func (x CalibrationOperation) String() string {
	return proto.EnumName(CalibrationOperation_name, int32(x))
}

func (CalibrationOperation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_822d05f6175684bb, []int{2}
}

type TempCalibrations int32

const (
	TempCalibrations_TEMP_NONE   TempCalibrations = 0
	TempCalibrations_TEMP_SINGLE TempCalibrations = 1
)

var TempCalibrations_name = map[int32]string{
	0: "TEMP_NONE",
	1: "TEMP_SINGLE",
}

var TempCalibrations_value = map[string]int32{
	"TEMP_NONE":   0,
	"TEMP_SINGLE": 1,
}

func (x TempCalibrations) String() string {
	return proto.EnumName(TempCalibrations_name, int32(x))
}

func (TempCalibrations) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_822d05f6175684bb, []int{3}
}

type DoCalibrations int32

const (
	DoCalibrations_DO_NONE       DoCalibrations = 0
	DoCalibrations_DO_ATMOSPHERE DoCalibrations = 1
	DoCalibrations_DO_ZERO       DoCalibrations = 2
)

var DoCalibrations_name = map[int32]string{
	0: "DO_NONE",
	1: "DO_ATMOSPHERE",
	2: "DO_ZERO",
}

var DoCalibrations_value = map[string]int32{
	"DO_NONE":       0,
	"DO_ATMOSPHERE": 1,
	"DO_ZERO":       2,
}

func (x DoCalibrations) String() string {
	return proto.EnumName(DoCalibrations_name, int32(x))
}

func (DoCalibrations) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_822d05f6175684bb, []int{4}
}

type PhCalibrations int32

const (
	PhCalibrations_PH_NONE   PhCalibrations = 0
	PhCalibrations_PH_LOW    PhCalibrations = 1
	PhCalibrations_PH_MIDDLE PhCalibrations = 2
	PhCalibrations_PH_HIGH   PhCalibrations = 4
)

var PhCalibrations_name = map[int32]string{
	0: "PH_NONE",
	1: "PH_LOW",
	2: "PH_MIDDLE",
	4: "PH_HIGH",
}

var PhCalibrations_value = map[string]int32{
	"PH_NONE":   0,
	"PH_LOW":    1,
	"PH_MIDDLE": 2,
	"PH_HIGH":   4,
}

func (x PhCalibrations) String() string {
	return proto.EnumName(PhCalibrations_name, int32(x))
}

func (PhCalibrations) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_822d05f6175684bb, []int{5}
}

type EcCalibrations int32

const (
	EcCalibrations_EC_NONE      EcCalibrations = 0
	EcCalibrations_EC_DRY       EcCalibrations = 1
	EcCalibrations_EC_SINGLE    EcCalibrations = 2
	EcCalibrations_EC_DUAL_LOW  EcCalibrations = 4
	EcCalibrations_EC_DUAL_HIGH EcCalibrations = 8
)

var EcCalibrations_name = map[int32]string{
	0: "EC_NONE",
	1: "EC_DRY",
	2: "EC_SINGLE",
	4: "EC_DUAL_LOW",
	8: "EC_DUAL_HIGH",
}

var EcCalibrations_value = map[string]int32{
	"EC_NONE":      0,
	"EC_DRY":       1,
	"EC_SINGLE":    2,
	"EC_DUAL_LOW":  4,
	"EC_DUAL_HIGH": 8,
}

func (x EcCalibrations) String() string {
	return proto.EnumName(EcCalibrations_name, int32(x))
}

func (EcCalibrations) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_822d05f6175684bb, []int{6}
}

type OrpCalibrations int32

const (
	OrpCalibrations_ORP_NONE   OrpCalibrations = 0
	OrpCalibrations_ORP_SINGLE OrpCalibrations = 1
)

var OrpCalibrations_name = map[int32]string{
	0: "ORP_NONE",
	1: "ORP_SINGLE",
}

var OrpCalibrations_value = map[string]int32{
	"ORP_NONE":   0,
	"ORP_SINGLE": 1,
}

func (x OrpCalibrations) String() string {
	return proto.EnumName(OrpCalibrations_name, int32(x))
}

func (OrpCalibrations) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_822d05f6175684bb, []int{7}
}

type ReplyType int32

const (
	ReplyType_REPLY_NONE          ReplyType = 0
	ReplyType_REPLY_RETRY         ReplyType = 1
	ReplyType_REPLY_ERROR         ReplyType = 2
	ReplyType_REPLY_ATLAS_COMMAND ReplyType = 3
)

var ReplyType_name = map[int32]string{
	0: "REPLY_NONE",
	1: "REPLY_RETRY",
	2: "REPLY_ERROR",
	3: "REPLY_ATLAS_COMMAND",
}

var ReplyType_value = map[string]int32{
	"REPLY_NONE":          0,
	"REPLY_RETRY":         1,
	"REPLY_ERROR":         2,
	"REPLY_ATLAS_COMMAND": 3,
}

func (x ReplyType) String() string {
	return proto.EnumName(ReplyType_name, int32(x))
}

func (ReplyType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_822d05f6175684bb, []int{8}
}

type ErrorType int32

const (
	ErrorType_NONE       ErrorType = 0
	ErrorType_GENERAL    ErrorType = 1
	ErrorType_UNEXPECTED ErrorType = 2
)

var ErrorType_name = map[int32]string{
	0: "NONE",
	1: "GENERAL",
	2: "UNEXPECTED",
}

var ErrorType_value = map[string]int32{
	"NONE":       0,
	"GENERAL":    1,
	"UNEXPECTED": 2,
}

func (x ErrorType) String() string {
	return proto.EnumName(ErrorType_name, int32(x))
}

func (ErrorType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_822d05f6175684bb, []int{9}
}

type AtlasCalibrationCommand struct {
	Operation            CalibrationOperation `protobuf:"varint,1,opt,name=operation,proto3,enum=fk_atlas.CalibrationOperation" json:"operation,omitempty"`
	Temp                 TempCalibrations     `protobuf:"varint,2,opt,name=temp,proto3,enum=fk_atlas.TempCalibrations" json:"temp,omitempty"`
	DissolvedOxygen      DoCalibrations       `protobuf:"varint,3,opt,name=dissolvedOxygen,proto3,enum=fk_atlas.DoCalibrations" json:"dissolvedOxygen,omitempty"`
	Ph                   PhCalibrations       `protobuf:"varint,4,opt,name=ph,proto3,enum=fk_atlas.PhCalibrations" json:"ph,omitempty"`
	Ec                   EcCalibrations       `protobuf:"varint,5,opt,name=ec,proto3,enum=fk_atlas.EcCalibrations" json:"ec,omitempty"`
	Orp                  OrpCalibrations      `protobuf:"varint,6,opt,name=orp,proto3,enum=fk_atlas.OrpCalibrations" json:"orp,omitempty"`
	Value                float32              `protobuf:"fixed32,7,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AtlasCalibrationCommand) Reset()         { *m = AtlasCalibrationCommand{} }
func (m *AtlasCalibrationCommand) String() string { return proto.CompactTextString(m) }
func (*AtlasCalibrationCommand) ProtoMessage()    {}
func (*AtlasCalibrationCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_822d05f6175684bb, []int{0}
}

func (m *AtlasCalibrationCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AtlasCalibrationCommand.Unmarshal(m, b)
}
func (m *AtlasCalibrationCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AtlasCalibrationCommand.Marshal(b, m, deterministic)
}
func (m *AtlasCalibrationCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AtlasCalibrationCommand.Merge(m, src)
}
func (m *AtlasCalibrationCommand) XXX_Size() int {
	return xxx_messageInfo_AtlasCalibrationCommand.Size(m)
}
func (m *AtlasCalibrationCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_AtlasCalibrationCommand.DiscardUnknown(m)
}

var xxx_messageInfo_AtlasCalibrationCommand proto.InternalMessageInfo

func (m *AtlasCalibrationCommand) GetOperation() CalibrationOperation {
	if m != nil {
		return m.Operation
	}
	return CalibrationOperation_CALIBRATION_NONE
}

func (m *AtlasCalibrationCommand) GetTemp() TempCalibrations {
	if m != nil {
		return m.Temp
	}
	return TempCalibrations_TEMP_NONE
}

func (m *AtlasCalibrationCommand) GetDissolvedOxygen() DoCalibrations {
	if m != nil {
		return m.DissolvedOxygen
	}
	return DoCalibrations_DO_NONE
}

func (m *AtlasCalibrationCommand) GetPh() PhCalibrations {
	if m != nil {
		return m.Ph
	}
	return PhCalibrations_PH_NONE
}

func (m *AtlasCalibrationCommand) GetEc() EcCalibrations {
	if m != nil {
		return m.Ec
	}
	return EcCalibrations_EC_NONE
}

func (m *AtlasCalibrationCommand) GetOrp() OrpCalibrations {
	if m != nil {
		return m.Orp
	}
	return OrpCalibrations_ORP_NONE
}

func (m *AtlasCalibrationCommand) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type TwoWireQuery struct {
	Read                 uint32   `protobuf:"varint,1,opt,name=read,proto3" json:"read,omitempty"`
	Write                uint32   `protobuf:"varint,2,opt,name=write,proto3" json:"write,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TwoWireQuery) Reset()         { *m = TwoWireQuery{} }
func (m *TwoWireQuery) String() string { return proto.CompactTextString(m) }
func (*TwoWireQuery) ProtoMessage()    {}
func (*TwoWireQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_822d05f6175684bb, []int{1}
}

func (m *TwoWireQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TwoWireQuery.Unmarshal(m, b)
}
func (m *TwoWireQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TwoWireQuery.Marshal(b, m, deterministic)
}
func (m *TwoWireQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TwoWireQuery.Merge(m, src)
}
func (m *TwoWireQuery) XXX_Size() int {
	return xxx_messageInfo_TwoWireQuery.Size(m)
}
func (m *TwoWireQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_TwoWireQuery.DiscardUnknown(m)
}

var xxx_messageInfo_TwoWireQuery proto.InternalMessageInfo

func (m *TwoWireQuery) GetRead() uint32 {
	if m != nil {
		return m.Read
	}
	return 0
}

func (m *TwoWireQuery) GetWrite() uint32 {
	if m != nil {
		return m.Write
	}
	return 0
}

func (m *TwoWireQuery) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type WireAtlasQuery struct {
	Type                 QueryType                `protobuf:"varint,1,opt,name=type,proto3,enum=fk_atlas.QueryType" json:"type,omitempty"`
	Calibration          *AtlasCalibrationCommand `protobuf:"bytes,2,opt,name=calibration,proto3" json:"calibration,omitempty"`
	Wire                 *TwoWireQuery            `protobuf:"bytes,3,opt,name=wire,proto3" json:"wire,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *WireAtlasQuery) Reset()         { *m = WireAtlasQuery{} }
func (m *WireAtlasQuery) String() string { return proto.CompactTextString(m) }
func (*WireAtlasQuery) ProtoMessage()    {}
func (*WireAtlasQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_822d05f6175684bb, []int{2}
}

func (m *WireAtlasQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WireAtlasQuery.Unmarshal(m, b)
}
func (m *WireAtlasQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WireAtlasQuery.Marshal(b, m, deterministic)
}
func (m *WireAtlasQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WireAtlasQuery.Merge(m, src)
}
func (m *WireAtlasQuery) XXX_Size() int {
	return xxx_messageInfo_WireAtlasQuery.Size(m)
}
func (m *WireAtlasQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_WireAtlasQuery.DiscardUnknown(m)
}

var xxx_messageInfo_WireAtlasQuery proto.InternalMessageInfo

func (m *WireAtlasQuery) GetType() QueryType {
	if m != nil {
		return m.Type
	}
	return QueryType_QUERY_NONE
}

func (m *WireAtlasQuery) GetCalibration() *AtlasCalibrationCommand {
	if m != nil {
		return m.Calibration
	}
	return nil
}

func (m *WireAtlasQuery) GetWire() *TwoWireQuery {
	if m != nil {
		return m.Wire
	}
	return nil
}

type AtlasCalibrationStatus struct {
	Type                 SensorType       `protobuf:"varint,1,opt,name=type,proto3,enum=fk_atlas.SensorType" json:"type,omitempty"`
	Time                 uint32           `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Temp                 TempCalibrations `protobuf:"varint,3,opt,name=temp,proto3,enum=fk_atlas.TempCalibrations" json:"temp,omitempty"`
	DissolvedOxygen      DoCalibrations   `protobuf:"varint,4,opt,name=dissolvedOxygen,proto3,enum=fk_atlas.DoCalibrations" json:"dissolvedOxygen,omitempty"`
	Ph                   PhCalibrations   `protobuf:"varint,5,opt,name=ph,proto3,enum=fk_atlas.PhCalibrations" json:"ph,omitempty"`
	Ec                   EcCalibrations   `protobuf:"varint,6,opt,name=ec,proto3,enum=fk_atlas.EcCalibrations" json:"ec,omitempty"`
	Orp                  OrpCalibrations  `protobuf:"varint,7,opt,name=orp,proto3,enum=fk_atlas.OrpCalibrations" json:"orp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AtlasCalibrationStatus) Reset()         { *m = AtlasCalibrationStatus{} }
func (m *AtlasCalibrationStatus) String() string { return proto.CompactTextString(m) }
func (*AtlasCalibrationStatus) ProtoMessage()    {}
func (*AtlasCalibrationStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_822d05f6175684bb, []int{3}
}

func (m *AtlasCalibrationStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AtlasCalibrationStatus.Unmarshal(m, b)
}
func (m *AtlasCalibrationStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AtlasCalibrationStatus.Marshal(b, m, deterministic)
}
func (m *AtlasCalibrationStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AtlasCalibrationStatus.Merge(m, src)
}
func (m *AtlasCalibrationStatus) XXX_Size() int {
	return xxx_messageInfo_AtlasCalibrationStatus.Size(m)
}
func (m *AtlasCalibrationStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_AtlasCalibrationStatus.DiscardUnknown(m)
}

var xxx_messageInfo_AtlasCalibrationStatus proto.InternalMessageInfo

func (m *AtlasCalibrationStatus) GetType() SensorType {
	if m != nil {
		return m.Type
	}
	return SensorType_SENSOR_NONE
}

func (m *AtlasCalibrationStatus) GetTime() uint32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *AtlasCalibrationStatus) GetTemp() TempCalibrations {
	if m != nil {
		return m.Temp
	}
	return TempCalibrations_TEMP_NONE
}

func (m *AtlasCalibrationStatus) GetDissolvedOxygen() DoCalibrations {
	if m != nil {
		return m.DissolvedOxygen
	}
	return DoCalibrations_DO_NONE
}

func (m *AtlasCalibrationStatus) GetPh() PhCalibrations {
	if m != nil {
		return m.Ph
	}
	return PhCalibrations_PH_NONE
}

func (m *AtlasCalibrationStatus) GetEc() EcCalibrations {
	if m != nil {
		return m.Ec
	}
	return EcCalibrations_EC_NONE
}

func (m *AtlasCalibrationStatus) GetOrp() OrpCalibrations {
	if m != nil {
		return m.Orp
	}
	return OrpCalibrations_ORP_NONE
}

type TwoWireReply struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TwoWireReply) Reset()         { *m = TwoWireReply{} }
func (m *TwoWireReply) String() string { return proto.CompactTextString(m) }
func (*TwoWireReply) ProtoMessage()    {}
func (*TwoWireReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_822d05f6175684bb, []int{4}
}

func (m *TwoWireReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TwoWireReply.Unmarshal(m, b)
}
func (m *TwoWireReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TwoWireReply.Marshal(b, m, deterministic)
}
func (m *TwoWireReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TwoWireReply.Merge(m, src)
}
func (m *TwoWireReply) XXX_Size() int {
	return xxx_messageInfo_TwoWireReply.Size(m)
}
func (m *TwoWireReply) XXX_DiscardUnknown() {
	xxx_messageInfo_TwoWireReply.DiscardUnknown(m)
}

var xxx_messageInfo_TwoWireReply proto.InternalMessageInfo

func (m *TwoWireReply) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Error struct {
	Type                 ErrorType `protobuf:"varint,1,opt,name=type,proto3,enum=fk_atlas.ErrorType" json:"type,omitempty"`
	Message              string    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_822d05f6175684bb, []int{5}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetType() ErrorType {
	if m != nil {
		return m.Type
	}
	return ErrorType_NONE
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type WireAtlasReply struct {
	Type                 ReplyType               `protobuf:"varint,1,opt,name=type,proto3,enum=fk_atlas.ReplyType" json:"type,omitempty"`
	Errors               []*Error                `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Calibration          *AtlasCalibrationStatus `protobuf:"bytes,3,opt,name=calibration,proto3" json:"calibration,omitempty"`
	Wire                 *TwoWireReply           `protobuf:"bytes,4,opt,name=wire,proto3" json:"wire,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *WireAtlasReply) Reset()         { *m = WireAtlasReply{} }
func (m *WireAtlasReply) String() string { return proto.CompactTextString(m) }
func (*WireAtlasReply) ProtoMessage()    {}
func (*WireAtlasReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_822d05f6175684bb, []int{6}
}

func (m *WireAtlasReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WireAtlasReply.Unmarshal(m, b)
}
func (m *WireAtlasReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WireAtlasReply.Marshal(b, m, deterministic)
}
func (m *WireAtlasReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WireAtlasReply.Merge(m, src)
}
func (m *WireAtlasReply) XXX_Size() int {
	return xxx_messageInfo_WireAtlasReply.Size(m)
}
func (m *WireAtlasReply) XXX_DiscardUnknown() {
	xxx_messageInfo_WireAtlasReply.DiscardUnknown(m)
}

var xxx_messageInfo_WireAtlasReply proto.InternalMessageInfo

func (m *WireAtlasReply) GetType() ReplyType {
	if m != nil {
		return m.Type
	}
	return ReplyType_REPLY_NONE
}

func (m *WireAtlasReply) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *WireAtlasReply) GetCalibration() *AtlasCalibrationStatus {
	if m != nil {
		return m.Calibration
	}
	return nil
}

func (m *WireAtlasReply) GetWire() *TwoWireReply {
	if m != nil {
		return m.Wire
	}
	return nil
}

func init() {
	proto.RegisterEnum("fk_atlas.SensorType", SensorType_name, SensorType_value)
	proto.RegisterEnum("fk_atlas.QueryType", QueryType_name, QueryType_value)
	proto.RegisterEnum("fk_atlas.CalibrationOperation", CalibrationOperation_name, CalibrationOperation_value)
	proto.RegisterEnum("fk_atlas.TempCalibrations", TempCalibrations_name, TempCalibrations_value)
	proto.RegisterEnum("fk_atlas.DoCalibrations", DoCalibrations_name, DoCalibrations_value)
	proto.RegisterEnum("fk_atlas.PhCalibrations", PhCalibrations_name, PhCalibrations_value)
	proto.RegisterEnum("fk_atlas.EcCalibrations", EcCalibrations_name, EcCalibrations_value)
	proto.RegisterEnum("fk_atlas.OrpCalibrations", OrpCalibrations_name, OrpCalibrations_value)
	proto.RegisterEnum("fk_atlas.ReplyType", ReplyType_name, ReplyType_value)
	proto.RegisterEnum("fk_atlas.ErrorType", ErrorType_name, ErrorType_value)
	proto.RegisterType((*AtlasCalibrationCommand)(nil), "fk_atlas.AtlasCalibrationCommand")
	proto.RegisterType((*TwoWireQuery)(nil), "fk_atlas.TwoWireQuery")
	proto.RegisterType((*WireAtlasQuery)(nil), "fk_atlas.WireAtlasQuery")
	proto.RegisterType((*AtlasCalibrationStatus)(nil), "fk_atlas.AtlasCalibrationStatus")
	proto.RegisterType((*TwoWireReply)(nil), "fk_atlas.TwoWireReply")
	proto.RegisterType((*Error)(nil), "fk_atlas.Error")
	proto.RegisterType((*WireAtlasReply)(nil), "fk_atlas.WireAtlasReply")
}

func init() { proto.RegisterFile("fk-atlas.proto", fileDescriptor_822d05f6175684bb) }

var fileDescriptor_822d05f6175684bb = []byte{
	// 839 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x51, 0x6f, 0xa3, 0x46,
	0x10, 0x2e, 0x18, 0xdb, 0xf1, 0x38, 0xb1, 0xf7, 0x36, 0x69, 0x8e, 0xb6, 0x52, 0x95, 0xfa, 0xe5,
	0x2c, 0xaa, 0xa6, 0x92, 0xfb, 0xda, 0x3e, 0x10, 0x58, 0xc5, 0xae, 0xb0, 0xe1, 0x16, 0xd2, 0x6b,
	0xda, 0x07, 0x8b, 0x8b, 0xf7, 0x2e, 0x56, 0x6c, 0x83, 0x80, 0x5c, 0xea, 0xbf, 0xd4, 0xbf, 0xd2,
	0xb7, 0xfe, 0x84, 0xfe, 0x92, 0x6a, 0x17, 0x03, 0x8b, 0x75, 0x96, 0xa2, 0xbc, 0xed, 0xcc, 0x7c,
	0xdf, 0xcc, 0xec, 0xec, 0x37, 0x00, 0xbd, 0x0f, 0x0f, 0x3f, 0x84, 0xd9, 0x2a, 0x4c, 0x2f, 0xe3,
	0x24, 0xca, 0x22, 0x7c, 0xf4, 0xe1, 0x61, 0x2e, 0xec, 0xc1, 0x7f, 0x2a, 0xbc, 0x36, 0xf9, 0xc9,
	0x0a, 0x57, 0xcb, 0xf7, 0x49, 0x98, 0x2d, 0xa3, 0x8d, 0x15, 0xad, 0xd7, 0xe1, 0x66, 0x81, 0x7f,
	0x86, 0x4e, 0x14, 0xb3, 0xdc, 0xa7, 0x2b, 0x17, 0xca, 0xb0, 0x37, 0xfa, 0xf6, 0xb2, 0x60, 0x5e,
	0x4a, 0x04, 0xb7, 0x40, 0xd1, 0x8a, 0x80, 0x2f, 0x41, 0xcb, 0xd8, 0x3a, 0xd6, 0x55, 0x41, 0xfc,
	0xba, 0x22, 0x06, 0x6c, 0x1d, 0x4b, 0xe4, 0x94, 0x0a, 0x1c, 0xbe, 0x82, 0xfe, 0x62, 0x99, 0xa6,
	0xd1, 0xea, 0x13, 0x5b, 0xb8, 0x7f, 0x6d, 0x3f, 0xb2, 0x8d, 0xde, 0x10, 0x54, 0xbd, 0xa2, 0xda,
	0x51, 0x8d, 0xb8, 0x4f, 0xc0, 0x43, 0x50, 0xe3, 0x7b, 0x5d, 0xdb, 0xa7, 0x79, 0xf7, 0x35, 0x9a,
	0x1a, 0xdf, 0x73, 0x24, 0xbb, 0xd3, 0x9b, 0xfb, 0x48, 0x72, 0x57, 0x47, 0xb2, 0x3b, 0xfc, 0x3d,
	0x34, 0xa2, 0x24, 0xd6, 0x5b, 0x02, 0xfa, 0x55, 0x05, 0x75, 0x93, 0xfa, 0x2d, 0x38, 0x0a, 0x9f,
	0x41, 0xf3, 0x53, 0xb8, 0x7a, 0x64, 0x7a, 0xfb, 0x42, 0x19, 0xaa, 0x34, 0x37, 0x06, 0x0e, 0x1c,
	0x07, 0x4f, 0xd1, 0xbb, 0x65, 0xc2, 0xde, 0x3e, 0xb2, 0x64, 0x8b, 0x31, 0x68, 0x09, 0x0b, 0x17,
	0x62, 0xa6, 0x27, 0x54, 0x9c, 0x39, 0xf3, 0x29, 0x59, 0x66, 0x4c, 0xcc, 0xeb, 0x84, 0xe6, 0x06,
	0x47, 0x2e, 0xc2, 0x2c, 0x14, 0x93, 0x38, 0xa6, 0xe2, 0x3c, 0xf8, 0x5b, 0x81, 0x1e, 0xcf, 0x25,
	0x9e, 0x2d, 0x4f, 0xf8, 0x06, 0xb4, 0x6c, 0x1b, 0xb3, 0xdd, 0x23, 0x9d, 0x56, 0x4d, 0x8a, 0x70,
	0xb0, 0x8d, 0x19, 0x15, 0x00, 0x6c, 0x41, 0xf7, 0xae, 0x6a, 0x5a, 0xd4, 0xea, 0x8e, 0xbe, 0xab,
	0xf0, 0x07, 0xa4, 0x40, 0x65, 0x16, 0x36, 0x40, 0x7b, 0x5a, 0x26, 0x4c, 0x34, 0xd5, 0x1d, 0x9d,
	0x4b, 0x2f, 0x2b, 0x5d, 0x92, 0x0a, 0xcc, 0xe0, 0x1f, 0x15, 0xce, 0xf7, 0x93, 0xfa, 0x59, 0x98,
	0x3d, 0xa6, 0x78, 0x58, 0x6b, 0xfa, 0xac, 0x4a, 0xe3, 0xb3, 0x4d, 0x1a, 0x25, 0x52, 0xd7, 0x18,
	0xb4, 0x6c, 0xb9, 0x2e, 0x46, 0x23, 0xce, 0xa5, 0xbc, 0x1a, 0x2f, 0x97, 0x97, 0xf6, 0x32, 0x79,
	0x35, 0x9f, 0x2d, 0xaf, 0xd6, 0xf3, 0xe5, 0xd5, 0x7e, 0x8e, 0xbc, 0x06, 0x83, 0x52, 0x48, 0x94,
	0xc5, 0xab, 0x6d, 0x29, 0x0f, 0x45, 0x92, 0xc7, 0xaf, 0xd0, 0x24, 0x49, 0x12, 0x25, 0x87, 0x45,
	0x21, 0xc2, 0xd2, 0x78, 0x75, 0x68, 0xaf, 0x59, 0x9a, 0x86, 0x1f, 0xf3, 0x09, 0x77, 0x68, 0x61,
	0x0e, 0xfe, 0x95, 0xa5, 0x96, 0x97, 0x3c, 0x98, 0x55, 0x84, 0xa5, 0xac, 0x6f, 0xa0, 0xc5, 0x78,
	0xa1, 0x54, 0x57, 0x2f, 0x1a, 0xc3, 0xee, 0xa8, 0xbf, 0xd7, 0x00, 0xdd, 0x85, 0xf1, 0x55, 0x5d,
	0x93, 0xb9, 0xaa, 0x2e, 0x0e, 0x6b, 0x32, 0x97, 0xcf, 0xe7, 0x25, 0xa9, 0x1d, 0x90, 0xa4, 0x68,
	0x2e, 0x97, 0xa4, 0xf1, 0x00, 0x50, 0x29, 0x0c, 0xf7, 0xa1, 0xeb, 0x93, 0x99, 0xef, 0xd2, 0xf9,
	0xcc, 0x9d, 0x11, 0xf4, 0x05, 0x3e, 0x81, 0xce, 0xce, 0xe1, 0x8d, 0x91, 0x22, 0xc5, 0x03, 0x32,
	0xf5, 0x90, 0x8a, 0x7b, 0x00, 0x3b, 0x87, 0x4b, 0x3d, 0xd4, 0x90, 0xf0, 0xb6, 0x8b, 0x34, 0xc9,
	0x24, 0x16, 0x6a, 0x1a, 0xdf, 0x40, 0xa7, 0xdc, 0x41, 0x4e, 0x7d, 0x7b, 0x43, 0xe8, 0xed, 0xae,
	0x94, 0x11, 0xc3, 0xd9, 0xe7, 0xbe, 0xa2, 0xf8, 0x0c, 0x90, 0x65, 0x3a, 0x93, 0x2b, 0x6a, 0x06,
	0x13, 0x77, 0x56, 0x34, 0x76, 0x0e, 0x58, 0xf6, 0xfa, 0x81, 0x19, 0xdc, 0xf8, 0x48, 0xc1, 0x5f,
	0xc2, 0x2b, 0xd9, 0x6f, 0x39, 0xc4, 0xa4, 0x48, 0xc5, 0xa7, 0xd0, 0xaf, 0xc1, 0x49, 0x80, 0x1a,
	0xc6, 0x08, 0xd0, 0xfe, 0x7e, 0xf0, 0x8e, 0xf9, 0xd5, 0x8a, 0x32, 0x7d, 0xe8, 0x0a, 0xd3, 0x9f,
	0xcc, 0xae, 0x1d, 0x82, 0x14, 0xe3, 0x17, 0xe8, 0xd5, 0x17, 0x03, 0x77, 0xa1, 0x6d, 0xbb, 0x05,
	0xfe, 0x15, 0x9c, 0xd8, 0xee, 0xdc, 0x0c, 0xa6, 0xae, 0xef, 0x8d, 0x09, 0x25, 0x48, 0xd9, 0xc5,
	0xff, 0x20, 0xd4, 0x45, 0xaa, 0x41, 0xa0, 0x57, 0x5f, 0x10, 0x1e, 0xf6, 0xc6, 0x05, 0x1d, 0xa0,
	0xe5, 0x8d, 0xe7, 0x8e, 0xfb, 0x0e, 0x29, 0xbc, 0x13, 0x6f, 0x3c, 0x9f, 0x4e, 0x6c, 0xdb, 0x21,
	0x48, 0xdd, 0xe1, 0xc6, 0x93, 0xeb, 0x31, 0xd2, 0x8c, 0x3f, 0xa1, 0x57, 0xdf, 0x1e, 0x1e, 0x26,
	0x96, 0x94, 0x86, 0x58, 0x73, 0x9b, 0xde, 0xe6, 0x69, 0x88, 0x55, 0xf4, 0xaf, 0xf2, 0x0b, 0xf1,
	0xd0, 0x8d, 0xe9, 0x88, 0x32, 0x1a, 0x46, 0x70, 0x5c, 0x38, 0x44, 0xf2, 0x23, 0xe3, 0x47, 0xe8,
	0xef, 0xed, 0x1b, 0x3e, 0x86, 0x23, 0x97, 0x96, 0x43, 0xe9, 0x01, 0x70, 0xab, 0x9c, 0xc9, 0x6f,
	0xd0, 0x29, 0xf5, 0xce, 0x83, 0x94, 0x78, 0xce, 0xad, 0x34, 0xc1, 0xdc, 0xa6, 0x24, 0x10, 0x0d,
	0x95, 0x0e, 0x42, 0xa9, 0xcb, 0xdf, 0xe6, 0x35, 0x9c, 0xe6, 0x0e, 0x33, 0x70, 0x4c, 0x7f, 0x6e,
	0xb9, 0xd3, 0xa9, 0x39, 0xb3, 0xc5, 0xfb, 0x74, 0xca, 0xed, 0xc4, 0x47, 0xa0, 0xed, 0x32, 0x76,
	0xa1, 0x7d, 0x4d, 0x66, 0x84, 0x9a, 0x0e, 0x52, 0x78, 0xb9, 0x9b, 0x19, 0xf9, 0xdd, 0x23, 0x56,
	0x40, 0x6c, 0xa4, 0xbe, 0x6f, 0x89, 0x7f, 0xfa, 0x4f, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0xde,
	0x9b, 0xa6, 0x84, 0xe5, 0x07, 0x00, 0x00,
}
