/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev */

#include "fk-atlas.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(fk_atlas_AtlasCommand, fk_atlas_AtlasCommand, AUTO)


PB_BIND(fk_atlas_AtlasReply, fk_atlas_AtlasReply, AUTO)


PB_BIND(fk_atlas_WireAtlasQuery, fk_atlas_WireAtlasQuery, AUTO)


PB_BIND(fk_atlas_Error, fk_atlas_Error, AUTO)


PB_BIND(fk_atlas_WireAtlasReply, fk_atlas_WireAtlasReply, AUTO)







/* @@protoc_insertion_point(eof) */
